<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice - Mellow Vault</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #333; font-size: 14px; padding: 20px; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #28a745; padding-bottom: 10px; }
        .logo { height: 60px; }
        .company-details { text-align: right; }
        .company-details h2 { margin: 0; color: #28a745; }
        .section-title { color: #28a745; margin-top: 30px; margin-bottom: 10px; font-size: 18px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #f9f9f9; font-weight: bold; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #aaa; }
    </style>
</head>
<body>

    <div class="header">
        <div>
            <img src="https://mellowvault.com/public/upload/header/1628667601.png" alt="Company Logo" width="100px" height="100px" class="logo">
        </div>
        <div class="company-details">
            <h2>Mellow Vault</h2>
            <p>
                123 Business Street<br>
                City, State ZIP<br>
                Email: support@mellowvault.com<br>
                Phone: +91-9876543210
            </p>
        </div>
    </div>

    <h1 style="text-align: center; color: #28a745; margin-top: 30px;">Invoice</h1>

    {{-- Employer Section --}}
    <h3 class="section-title">Employer Details</h3>
    <table>
        <tr><th>Full Name</th><td>{{ $empData['fname'] ?? 'N/A' }} {{ $empData['lname'] ?? '' }}</td></tr>
        <tr><th>Email</th><td>{{ $empData['email'] ?? 'N/A' }}</td></tr>
        <tr><th>Phone</th><td>{{ $empData['phone'] ?? 'N/A' }}</td></tr>
        <tr><th>Company Name</th><td>{{ $empData['company_name'] ?? 'N/A' }}</td></tr>
        <tr><th>Address</th><td>{{ $empData['address'] ?? 'N/A' }}</td></tr>
    </table>

    {{-- Transaction Section --}}
    <h3 class="section-title">Transaction Details</h3>
    <table>
        <tr><th>Transaction ID</th><td>{{ $orderData['razorpay_payment_id'] ?? 'N/A' }}</td></tr>
        <tr><th>Order ID</th><td>{{ $orderData['mer_transaction_id'] ?? 'N/A' }}</td></tr>
        <tr><th>Amount Paid</th><td>₹{{ number_format($orderData['amount_paid'] ?? 0, 2) }}</td></tr>
        <tr><th>Payment Method</th><td>{{ $orderData['type'] ?? 'Online' }}</td></tr>
        <tr><th>Payment Date</th><td>{{ \Carbon\Carbon::now()->format('d M Y, h:i A') }}</td></tr>
    </table>

    {{-- Calculation --}}
    @php
        $subtotal = ($orderData['amount_paid'] ?? 0) / 1.18;
        $gst = $subtotal * 0.18;
    @endphp

    {{-- Invoice Summary --}}
    <h3 class="section-title">Invoice Summary</h3>
    <table>
        <tr><th>Subtotal (Excl. GST)</th><td>₹{{ number_format($subtotal, 2) }}</td></tr>
        <tr><th>GST (18%)</th><td>₹{{ number_format($gst, 2) }}</td></tr>
        <tr><th><strong>Grand Total</strong></th><td><strong>₹{{ number_format($orderData['amount_paid'] ?? 0, 2) }}</strong></td></tr>
    </table>

    {{-- Footer --}}
    <div class="footer">
        This invoice was generated by Mellow Vault. If you have questions, contact us at support@mellowvault.com
    </div>

</body>
</html>
